### PR TITLE
[FAILING] add failing spec

### PR DESCRIPTION
**Pull request by despairblue**

### CODE REVIEW

**Comment by despairblue** [comment]
@maximilianschmitt tripped over this again.

**Comment by despairblue** [comment]
@maximilianschmitt can I somehow check for the existence of an object?

**Comment by maximilianschmitt** [comment]
@despairblue the problem is that flat flattens everything all-the-way. There is an open pull request on flat: https://github.com/hughsk/flat/pull/41

**Comment by despairblue** [comment]
Doing some spring cleaning for my open PRs. @avlan replaced our usage of this lib with joi.

**Pull request closed without merging**
